name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Login to Hugging Face
      run: |
        pip install huggingface_hub
        huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}
    - name: Push to Hugging Face
      run: |
         huggingface-cli repo create news-sentiment-analysis e --type space --exist-ok
         git push https://huggingface.co/spaces/Avantika16/news-sentiment-analysis main
